// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDu4XB1-pcToAY2dpyzS5cmHswDSzd0pw',
    appId: '1:935368980876:web:25d1f3b340dc28afcefea9',
    messagingSenderId: '935368980876',
    projectId: 'edurise-9e5e6',
    authDomain: 'edurise-9e5e6.firebaseapp.com',
    storageBucket: 'edurise-9e5e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlGcF9EcnQPZNnsZMN1j6Uy4d_2pXHL7M',
    appId: '1:935368980876:android:1f9080c940bf7c22cefea9',
    messagingSenderId: '935368980876',
    projectId: 'edurise-9e5e6',
    storageBucket: 'edurise-9e5e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZrmJtkv3p4bcE-obQe5Yr9hf1g-L520',
    appId: '1:935368980876:ios:a1bd6209f31a19accefea9',
    messagingSenderId: '935368980876',
    projectId: 'edurise-9e5e6',
    storageBucket: 'edurise-9e5e6.firebasestorage.app',
    iosBundleId: 'com.example.edurise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZrmJtkv3p4bcE-obQe5Yr9hf1g-L520',
    appId: '1:935368980876:ios:a1bd6209f31a19accefea9',
    messagingSenderId: '935368980876',
    projectId: 'edurise-9e5e6',
    storageBucket: 'edurise-9e5e6.firebasestorage.app',
    iosBundleId: 'com.example.edurise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDu4XB1-pcToAY2dpyzS5cmHswDSzd0pw',
    appId: '1:935368980876:web:97c67b75962f244bcefea9',
    messagingSenderId: '935368980876',
    projectId: 'edurise-9e5e6',
    authDomain: 'edurise-9e5e6.firebaseapp.com',
    storageBucket: 'edurise-9e5e6.firebasestorage.app',
  );
}
